In [11]:
# Importing python libraries for analysis

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')

In [18]:
# Creating Dataframes from the excel files

data_folder = "data"

for file in os.listdir(data_folder):
    if file.endswith('.xlsx'):
        file_path = os.path.join(data_folder, file)
        df = pd.read_excel(file_path)
        globals()[f"df_{file.replace(".xlsx","").lower()}"] = df
        print(f"Created DataFrame: df_{file.replace(".xlsx","").lower()}")

Created DataFrame: df_dim_customer
Created DataFrame: df_dim_date
Created DataFrame: df_dim_geography
Created DataFrame: df_dim_products
Created DataFrame: df_dim_salesperson
Created DataFrame: df_fact_sales

### Cleaning DataFrames (df_dim_customer)

In [19]:
df_dim_customer.head(5)

  customer_id customer_name     segment    industry
0      C00001  Olivia Brown      Retail      Retail
1      C00002   Sneha Reddy      Retail          IT
2      C00003  Aarav Sharma  Government  Healthcare
3      C00004  David Wilson  Government  Healthcare
4      C00005    John Singh  Enterprise      Retail

In [21]:
df_dim_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   object
 1   customer_name  5000 non-null   object
 2   segment        5000 non-null   object
 3   industry       5000 non-null   object
dtypes: object(4)
memory usage: 156.4+ KB

In [22]:
# Checking Null Values

df_dim_customer.isnull().sum()

customer_id      0
customer_name    0
segment          0
industry         0
dtype: int64

In [30]:
# Checking Duplicated columns

In [31]:
df_dim_customer[df_dim_customer.duplicated()]

Empty DataFrame
Columns: [customer_id, customer_name, segment, industry]
Index: []

In [32]:
# checking distinct customer id across all rows

In [33]:
df_dim_customer.shape

(5000, 4)

In [26]:
df_dim_customer['customer_id'].nunique()

5000

In [34]:
# checking and fixing datatypes

In [35]:
df_dim_customer.dtypes

customer_id      object
customer_name    object
segment          object
industry         object
dtype: object

In [ ]:
# Checking for inconsistent formatting or spelling errors

In [36]:
df_dim_customer['segment'].unique()

array(['Retail', 'Government', 'Enterprise', 'SMB'], dtype=object)

In [37]:
df_dim_customer['industry'].unique()

array(['Retail', 'IT', 'Healthcare', 'Finance'], dtype=object)

### Cleaning DataFrame (df_dim_geography)

In [38]:
df_dim_geography.head()

   geo_id         region country          state         city
0       1   Asia-Pacific   India      Karnataka    Bengaluru
1       2  South America  Brazil      Sao Paulo    Sao Paulo
2       3         Europe  France  Ile-de-France        Paris
3       4  North America     USA     California  Los Angeles
4       5  North America  Canada        Ontario      Toronto

In [45]:
# Checking data info

In [46]:
df_dim_geography.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   geo_id   120 non-null    int64
 1   region   120 non-null    object
 2   country  120 non-null    object
 3   state    120 non-null    object
 4   city     120 non-null    object
dtypes: int64(1), object(4)
memory usage: 4.8+ KB

In [47]:
# Checking Null values

In [48]:
df_dim_geography.isnull().sum()

geo_id     0
region     0
country    0
state      0
city       0
dtype: int64

In [49]:
# Checking Duplicate values

In [50]:
df_dim_geography.duplicated().sum()

np.int64(0)

In [51]:
# Checking for distinct geo_id across all rows

In [52]:
df_dim_geography.shape

(120, 5)

In [53]:
df_dim_geography['geo_id'].nunique()

120

In [ ]:
# Checking for inconsistent formatting or spelling errors

In [54]:
df_dim_geography.columns

Index(['geo_id', 'region', 'country', 'state', 'city'], dtype='object')

In [55]:
df_dim_geography['region'].unique()

array(['Asia-Pacific', 'South America', 'Europe', 'North America',
       'Middle East'], dtype=object)

In [56]:
df_dim_geography['country'].unique()

array(['India', 'Brazil', 'France', 'USA', 'Canada', 'UAE', 'Argentina',
       'Japan', 'Australia', 'UK', 'Saudi Arabia', 'Germany'],
      dtype=object)

In [60]:
df_dim_geography['state'].unique()

array(['Karnataka', 'Sao Paulo', 'Ile-de-France', 'California', 'Ontario',
       'Texas', 'Dubai', 'Buenos Aires', 'Tokyo', 'Victoria', 'England',
       'Riyadh', 'Bavaria', 'Tamil Nadu'], dtype=object)

In [61]:
df_dim_geography['city'].unique()

array(['Bengaluru', 'Sao Paulo', 'Paris', 'Los Angeles', 'Toronto',
       'Dallas', 'Dubai', 'Buenos Aires', 'Tokyo', 'Melbourne', 'London',
       'Riyadh', 'Munich', 'Chennai'], dtype=object)

### Cleaning DataFrame (df_dim_products)

In [63]:
df_dim_products.head()

  product_id          product_name    category   brand
0      P0001  Business Switch 24 1  Networking    Dell
1      P0002        UltraView 24 1     Monitor   Cisco
2      P0003     Crystal Display 1     Monitor      HP
3      P0004           SSD 512GB 1     Storage   Cisco
4      P0005     Security Shield 1    Software  Lenovo

In [64]:
df_dim_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    300 non-null    object
 1   product_name  300 non-null    object
 2   category      300 non-null    object
 3   brand         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB

In [ ]:
# Checking Null values

In [65]:
df_dim_products.isnull().sum()

product_id      0
product_name    0
category        0
brand           0
dtype: int64

In [ ]:
# Checking Duplicate values

In [67]:
df_dim_products.duplicated().sum()

np.int64(0)

In [ ]:
# Checking for distinct product_id across all rows

In [68]:
df_dim_products.shape

(300, 4)

In [69]:
df_dim_products['product_id'].nunique()

300

In [ ]:
# Checking for inconsistent formatting or spelling errors

In [70]:
df_dim_products.columns

Index(['product_id', 'product_name', 'category', 'brand'], dtype='object')

In [71]:
df_dim_products['product_name'].unique()

array(['Business Switch 24 1', 'UltraView 24 1', 'Crystal Display 1',
       'SSD 512GB 1', 'Security Shield 1', 'SSD 512GB 2', 'SSD 1TB 1',
       'Business Switch 24 2', 'IdeaPad Slim 1', 'OfficeView 22 1',
       'Access Point Pro 1', 'OfficeView 22 2', 'USB Drive 128GB 1',
       'Cloud Backup 1', 'ERP Standard 1', 'OfficeView 22 3',
       'USB Drive 128GB 2', 'Network Hub 1', 'SSD 512GB 3',
       'ZenBook Air 1', 'ThinkBook Pro 14 1', 'External HDD 2TB 1',
       'Portable SSD 1', 'ProColor 27 1', 'SSD 1TB 2', 'VisionPro 27 1',
       'ERP Standard 2', 'ThinkBook Pro 14 2', 'Network Hub 2',
       'USB Drive 128GB 3', 'OfficeView 22 4', 'Cloud Backup 2',
       'WiFi Router AX6000 1', 'Network Hub 3', 'IdeaPad Slim 2',
       'External HDD 2TB 2', 'USB Drive 128GB 4', 'CRM Essentials 1',
       'SSD 512GB 4', 'Surface Laptop Go 1', 'Surface Laptop Go 2',
       'TravelMate Pro 1', 'Analytics Pro 1', 'Enterprise Firewall 1',
       'USB Drive 128GB 5', 'Latitude 15 1', 'Security Shield 2',
       'USB Drive 128GB 6', 'CRM Essentials 2', 'Analytics Pro 2',
       'SSD 512GB 5', 'UltraView 24 2', 'Analytics Pro 3',
       'Business Switch 24 3', 'Surface Laptop Go 3', 'Network Hub 4',
       'SSD 1TB 3', 'TravelMate Pro 2', 'UltraView 24 3',
       'Cloud Backup 3', 'TravelMate Pro 3', 'Enterprise Firewall 2',
       'OfficeView 22 5', 'Security Shield 3', 'Analytics Pro 4',
       'Enterprise Firewall 3', 'WiFi Router AX6000 2',
       'Security Shield 4', 'Analytics Pro 5', 'Network Hub 5',
       'WiFi Router AX6000 3', 'ZenBook Air 2', 'Crystal Display 2',
       'UltraView 24 4', 'Enterprise Firewall 4', 'CRM Essentials 3',
       'VisionPro 27 2', 'Crystal Display 3', 'NVMe Pro 2TB 1',
       'Business Switch 24 4', 'EliteBook X 1', 'Security Shield 5',
       'Enterprise Firewall 5', 'Mesh Router 1', 'OfficeView 22 6',
       'Portable SSD 2', 'OfficeView 22 7', 'ThinkBook Pro 14 3',
       'UltraView 24 5', 'Business Switch 24 5', 'VisionPro 27 3',
       'WiFi Router AX6000 4', 'Crystal Display 4', 'CRM Essentials 4',
       'SSD 512GB 6', 'OfficeView 22 8', 'WiFi Router AX6000 5',
       'SSD 512GB 7', 'CRM Essentials 5', 'Analytics Pro 6',
       'CurvedView 32 1', 'USB Drive 128GB 7', 'ERP Standard 3',
       'CurvedView 32 2', 'UltraView 24 6', 'Cloud Backup 4',
       'CurvedView 32 3', 'Portable SSD 3', 'Analytics Pro 7',
       'External HDD 2TB 3', 'ProColor 27 2', 'ZenBook Air 3',
       'ERP Standard 4', 'External HDD 2TB 4', 'USB Drive 128GB 8',
       'Office Suite 1', 'Business Switch 24 6', 'TravelMate Pro 4',
       'ERP Standard 5', 'VisionPro 27 4', 'ProColor 27 3',
       'UltraView 24 7', 'External HDD 2TB 5', 'USB Drive 128GB 9',
       'ZenBook Air 4', 'SSD 1TB 4', 'Latitude 15 2',
       'WiFi Router AX6000 6', 'CRM Essentials 6', 'Analytics Pro 8',
       'Office Suite 2', 'Mesh Router 2', 'CRM Essentials 7',
       'Cloud Backup 5', 'Office Suite 3', 'Surface Laptop Go 4',
       'ThinkBook Pro 14 4', 'IdeaPad Slim 3', 'Enterprise Firewall 6',
       'CRM Essentials 8', 'Security Shield 6', 'Surface Laptop Go 5',
       'Office Suite 4', 'CurvedView 32 4', 'Aspire Max 1',
       'NVMe Pro 2TB 2', 'SSD 1TB 5', 'Cloud Backup 6',
       'USB Drive 128GB 10', 'Office Suite 5', 'Portable SSD 4',
       'Business Switch 24 7', 'ERP Standard 6', 'Surface Laptop Go 6',
       'Network Hub 6', 'EliteBook X 2', 'Network Hub 7',
       'Portable SSD 5', 'Access Point Pro 2', 'Access Point Pro 3',
       'CRM Essentials 9', 'OfficeView 22 9', 'Office Suite 6',
       'WiFi Router AX6000 7', 'Latitude 15 3', 'UltraView 24 8',
       'Office Suite 7', 'Cloud Backup 7', 'Cloud Backup 8',
       'NVMe Pro 2TB 3', 'VisionPro 27 5', 'ProColor 27 4',
       'Network Hub 8', 'IdeaPad Slim 4', 'WiFi Router AX6000 8',
       'ERP Standard 7', 'CRM Essentials 10', 'Access Point Pro 4',
       'IdeaPad Slim 5', 'Mesh Router 3', 'SSD 512GB 8',
       'Access Point Pro 5', 'USB Drive 128GB 11', 'VisionPro 27 6',
       'Security Shield 7', 'SSD 512GB 9', 'Network Hub 9',
       'OfficeView 22 10', 'ERP Standard 8', 'ZenBook Air 5',
       'Office Suite 8', 'SSD 512GB 10', 'Business Switch 24 8',
       'Mesh Router 4', 'SSD 1TB 6', 'OfficeView 22 11',
       'ThinkBook Pro 14 5', 'Access Point Pro 6', 'NVMe Pro 2TB 4',
       'Latitude 15 4', 'Cloud Backup 9', 'Aspire Max 2', 'EliteBook X 3',
       'ThinkBook Pro 14 6', 'Network Hub 10', 'UltraView 24 9',
       'VisionPro 27 7', 'External HDD 2TB 6', 'Surface Laptop Go 7',
       'Crystal Display 5', 'External HDD 2TB 7', 'ProColor 27 5',
       'USB Drive 128GB 12', 'NVMe Pro 2TB 5', 'Portable SSD 6',
       'CRM Essentials 11', 'Cloud Backup 10', 'IdeaPad Slim 6',
       'External HDD 2TB 8', 'CRM Essentials 12', 'Mesh Router 5',
       'SSD 512GB 11', 'ProColor 27 6', 'ZenBook Air 6', 'Mesh Router 6',
       'Cloud Backup 11', 'CurvedView 32 5', 'Latitude 15 5',
       'Crystal Display 6', 'ERP Standard 9', 'Cloud Backup 12',
       'WiFi Router AX6000 9', 'ZenBook Air 7', 'Security Shield 8',
       'ThinkBook Pro 14 7', 'External HDD 2TB 9',
       'WiFi Router AX6000 10', 'Mesh Router 7', 'CRM Essentials 13',
       'Crystal Display 7', 'Security Shield 9', 'Security Shield 10',
       'USB Drive 128GB 13', 'Latitude 15 6', 'Surface Laptop Go 8',
       'CurvedView 32 6', 'Network Hub 11', 'Portable SSD 7',
       'CRM Essentials 14', 'TravelMate Pro 5', 'ERP Standard 10',
       'CRM Essentials 15', 'External HDD 2TB 10', 'NVMe Pro 2TB 6',
       'USB Drive 128GB 14', 'Office Suite 9', 'EliteBook X 4',
       'Security Shield 11', 'Latitude 15 7', 'Security Shield 12',
       'ThinkBook Pro 14 8', 'UltraView 24 10', 'External HDD 2TB 11',
       'Security Shield 13', 'Business Switch 24 9', 'VisionPro 27 8',
       'Office Suite 10', 'SSD 512GB 12', 'USB Drive 128GB 15',
       'SSD 1TB 7', 'Latitude 15 8', 'Access Point Pro 7',
       'VisionPro 27 9', 'Enterprise Firewall 7', 'Crystal Display 8',
       'Portable SSD 8', 'WiFi Router AX6000 11', 'CRM Essentials 16',
       'Aspire Max 3', 'USB Drive 128GB 16', 'UltraView 24 11',
       'ZenBook Air 8', 'Enterprise Firewall 8', 'UltraView 24 12',
       'SSD 512GB 13', 'VisionPro 27 10', 'TravelMate Pro 6',
       'OfficeView 22 12', 'Access Point Pro 8', 'VisionPro 27 11',
       'Business Switch 24 10', 'WiFi Router AX6000 12',
       'UltraView 24 13', 'Network Hub 12', 'Security Shield 14',
       'External HDD 2TB 12', 'ThinkBook Pro 14 9', 'VisionPro 27 12',
       'Enterprise Firewall 9', 'Network Hub 13'], dtype=object)

In [72]:
df_dim_products['category'].unique()

array(['Networking', 'Monitor', 'Storage', 'Software', 'Laptop'],
      dtype=object)

In [73]:
df_dim_products['brand'].unique()

array(['Dell', 'Cisco', 'HP', 'Lenovo', 'Microsoft'], dtype=object)

### Cleaning DataFrame (df_dim_date)

In [74]:
df_dim_date.head()

,date,day,day_name,month,month_name,quarter,year,month_year,year_quarter,financial_year,financial_quarter
0,2022-01-01,1,Saturday,1,January,Q1,2022,Jan-2022,2022-Q1,FY2021-22,Q4
1,2022-01-02,2,Sunday,1,January,Q1,2022,Jan-2022,2022-Q1,FY2021-22,Q4
2,2022-01-03,3,Monday,1,January,Q1,2022,Jan-2022,2022-Q1,FY2021-22,Q4
3,2022-01-04,4,Tuesday,1,January,Q1,2022,Jan-2022,2022-Q1,FY2021-22,Q4
4,2022-01-05,5,Wednesday,1,January,Q1,2022,Jan-2022,2022-Q1,FY2021-22,Q4

In [75]:
df_dim_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1461 non-null   object
 1   day                1461 non-null   int64
 2   day_name           1461 non-null   object
 3   month              1461 non-null   int64
 4   month_name         1461 non-null   object
 5   quarter            1461 non-null   object
 6   year               1461 non-null   int64
 7   month_year         1461 non-null   object
 8   year_quarter       1461 non-null   object
 9   financial_year     1461 non-null   object
 10  financial_quarter  1461 non-null   object
dtypes: int64(3), object(8)
memory usage: 125.7+ KB

In [ ]:
# Checking Null Values

In [76]:
df_dim_date.isnull().sum()

date                 0
day                  0
day_name             0
month                0
month_name           0
quarter              0
year                 0
month_year           0
year_quarter         0
financial_year       0
financial_quarter    0
dtype: int64

In [ ]:
# Checking Duplicate values

In [78]:
df_dim_date.duplicated().sum()

np.int64(0)

In [ ]:
# Verifying datatypes

In [93]:
df_dim_date.dtypes

date                 datetime64[ns]
day                           int64
day_name                     object
month                         int64
month_name                   object
quarter                      object
year                          int64
month_year                   object
year_quarter                 object
financial_year               object
financial_quarter            object
dtype: object

In [80]:
df_dim_date['date'] = pd.to_datetime(df_dim_date['date'])

In [ ]:
# Checking date range

In [83]:
print("Min-Date: ",df_dim_date['date'].min() )
print("Max-Date: ",df_dim_date['date'].max() )

Min-Date:  2022-01-01 00:00:00
Max-Date:  2025-12-31 00:00:00

In [ ]:
#Validate key columns

In [85]:
df_dim_date['month_name'].unique()

array(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype=object)

In [87]:
df_dim_date["day_name"].unique()

array(['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
       'Friday'], dtype=object)

In [92]:
df_dim_date['quarter'].unique()

array(['Q1', 'Q2', 'Q3', 'Q4'], dtype=object)

In [90]:
#Check for continuous dates

df_dim_date['date'].diff().value_counts()

date
1 days    1460
Name: count, dtype: int64

### Cleaning DataFrame (df_dim_salesperson)

In [94]:
df_dim_salesperson.head()

  salesperson_id salesperson_name             designation
0           S001   James Anderson         Sales Executive
1           S002     Olivia Brown  Senior Sales Executive
2           S003     Liam Johnson           Sales Manager
3           S004       Emma Davis           Sales Manager
4           S005      Noah Wilson  Senior Sales Executive

In [95]:
df_dim_salesperson.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   salesperson_id    100 non-null    object
 1   salesperson_name  100 non-null    object
 2   designation       100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB

In [ ]:
# Checking null values

In [97]:
df_dim_salesperson.isnull().sum()

salesperson_id      0
salesperson_name    0
designation         0
dtype: int64

In [ ]:
# Checking Duplicate Values

In [98]:
df_dim_salesperson.duplicated().sum()

np.int64(0)

In [ ]:
# Verifying datatypes

In [99]:
df_dim_salesperson.dtypes

salesperson_id      object
salesperson_name    object
designation         object
dtype: object

In [ ]:
#validdting data

In [100]:
df_dim_salesperson.columns

Index(['salesperson_id', 'salesperson_name', 'designation'], dtype='object')

In [101]:
df_dim_salesperson.shape

(100, 3)

In [102]:
df_dim_salesperson['salesperson_id'].nunique()

100

In [103]:
df_dim_salesperson['designation'].unique()

array(['Sales Executive', 'Senior Sales Executive', 'Sales Manager',
       'Regional Manager'], dtype=object)

### Cleaning DataFrame (df_fact_sales)

In [104]:
df_fact_sales.head()

,order_id,order_date,customer_id,product_id,geo_id,salesperson_id,quantity,unit_price,unit_cost,discount_percent,gross_sales,discount_amount,net_sales,profit
0,O000001,2025-08-14,C04634,P0085,62,S069,32,1225,796.25,10,39200,3920.0,35280.0,9800.00
1,O000002,2024-06-15,C03773,P0215,41,S036,46,1892,1229.80,5,87032,4351.6,82680.4,26109.60
2,O000003,2022-06-10,C00874,P0080,69,S062,9,336,218.40,10,3024,302.4,2721.6,756.00
3,O000004,2025-02-18,C01009,P0276,55,S032,31,1218,791.70,15,37758,5663.7,32094.3,7551.60
4,O000005,2025-02-14,C04102,P0147,118,S063,37,1549,1006.85,0,57313,0.0,57313.0,20059.55

In [105]:
df_fact_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75000 entries, 0 to 74999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          75000 non-null  object
 1   order_date        75000 non-null  object
 2   customer_id       75000 non-null  object
 3   product_id        75000 non-null  object
 4   geo_id            75000 non-null  int64
 5   salesperson_id    75000 non-null  object
 6   quantity          75000 non-null  int64
 7   unit_price        75000 non-null  int64
 8   unit_cost         75000 non-null  float64
 9   discount_percent  75000 non-null  int64
 10  gross_sales       75000 non-null  int64
 11  discount_amount   75000 non-null  float64
 12  net_sales         75000 non-null  float64
 13  profit            75000 non-null  float64
dtypes: float64(4), int64(5), object(5)
memory usage: 8.0+ MB

In [ ]:
# Checking for null values

In [107]:
df_fact_sales.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_id          0
geo_id              0
salesperson_id      0
quantity            0
unit_price          0
unit_cost           0
discount_percent    0
gross_sales         0
discount_amount     0
net_sales           0
profit              0
dtype: int64

In [ ]:
# Checking duplicate values

In [108]:
df_fact_sales.duplicated().sum()

np.int64(0)

In [ ]:
# Verifying datatypes

In [110]:
df_fact_sales.head(2)

,order_id,order_date,customer_id,product_id,geo_id,salesperson_id,quantity,unit_price,unit_cost,discount_percent,gross_sales,discount_amount,net_sales,profit
0,O000001,2025-08-14,C04634,P0085,62,S069,32,1225,796.25,10,39200,3920.0,35280.0,9800.0
1,O000002,2024-06-15,C03773,P0215,41,S036,46,1892,1229.80,5,87032,4351.6,82680.4,26109.6

In [115]:
df_fact_sales.dtypes

order_id                    object
order_date          datetime64[ns]
customer_id                 object
product_id                  object
geo_id                       int64
salesperson_id              object
quantity                     int64
unit_price                 float64
unit_cost                  float64
discount_percent             int64
gross_sales                  int64
discount_amount            float64
net_sales                  float64
profit                     float64
dtype: object

In [112]:
df_fact_sales['order_date'] = pd.to_datetime(df_fact_sales['order_date'])

In [114]:
df_fact_sales['unit_price'] = df_fact_sales['unit_price'].astype('float')

### Converting cleaned dataframes into csv files

In [116]:
output_folder = os.path.join("data", "cleaned_data")
os.makedirs(output_folder, exist_ok=True)


df_dim_customer.to_csv(os.path.join(output_folder, "dim_customer.csv"), index=False)
df_dim_date.to_csv(os.path.join(output_folder, "dim_date.csv"), index=False)
df_dim_geography.to_csv(os.path.join(output_folder, "dim_geography.csv"), index=False)
df_dim_products.to_csv(os.path.join(output_folder, "dim_products.csv"), index=False)
df_dim_salesperson.to_csv(os.path.join(output_folder, "dim_salesperson.csv"), index=False)
df_fact_sales.to_csv(os.path.join(output_folder, "fact_sales.csv"), index=False)